apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"PersistentVolume","metadata":{"annotations":{},"name":"postgres-volume"},"spec":{"accessModes":["ReadWriteOnce"],"capacity":{"storage":"2Gi"},"hostPath":{"path":"/data/postgres"},"storageClassName":"standard"}}
    pv.kubernetes.io/bound-by-controller: "yes"
  creationTimestamp: "2023-01-19T13:49:22Z"
  finalizers:
  - kubernetes.io/pv-protection
  name: postgres-volume
  resourceVersion: "4829"
  uid: 331a47e3-3969-4ce4-8bcd-569dabc59847
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 2Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: postgres-volume-claim
    namespace: default
    resourceVersion: "4826"
    uid: 7af0ce96-156f-4ead-9988-b501e6f420c0
  hostPath:
    path: /data/postgres
    type: ""
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  volumeMode: Filesystem
status:
  phase: Bound
