apiVersion: apps/v1

kind: Deployment

metadata:
  name: fastapi-deployment

spec:
  replicas: 4
  selector:
    matchLabels:
      app: fastapi

  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
      - name: fastapi-container
        image: app:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000 # Same as service target port
        env:
          - name: DB_HOST
            value: postgres-service
          - name: DB_PORT
            value: "5432"
