apiVersion: apps/v1

kind: Deployment

metadata:
  name: streamlit-deployment

spec:
  replicas: 2
  selector:
    matchLabels:
      app: streamlit
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: streamlit

    spec:
      containers:
      - name: streamlit-container
        image: streamlit-app:latest
        imagePullPolicy: Never

        resources:
          limits:
            memory: 512Mi
            cpu: "1"
          requests:
            memory: 256Mi
            cpu: "0.2"
        ports:
        - containerPort: 8501
        envFrom:
        - secretRef:
            name: postgres-secrets
        - configMapRef:
            name: postgres-env
