apiVersion: v1
kind: Service

metadata:
  name: streamlit-service

spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      name: service-port
      targetPort: 8501
      port: 8501
  selector:
    app: streamlit
